"""
Build mpob_annual.csv and gain_indonesia.csv from PDF-extracted data.
Then run process_mpob.py for derived fields.
"""

import pandas as pd
import numpy as np
import os

PROCESSED = r"C:\Users\arosenbaum\Downloads\ELNINO tracker\data\processed"
os.makedirs(PROCESSED, exist_ok=True)

# ─── MPOB Annual Data (from PDF extraction) ───────────────────────────────────
mpob_raw = [
    # ── 2010-2016 batch ──────────────────────────────────────────────────────
    {
        "year": 2010,
        "cpo_production_malaysia_mt": 16993717,
        "cpo_production_peninsular_mt": 9500000,
        "cpo_production_sabah_mt": 5300000,
        "cpo_production_sarawak_mt": 2200000,
        "oer_national_pct": 20.45,
        "oer_peninsular_pct": 19.91,
        "oer_sabah_pct": 21.33,
        "oer_sarawak_pct": 20.85,
        "ffb_yield_malaysia_t_per_ha": 18.03,
        "ffb_yield_peninsular_t_per_ha": None,
        "ffb_yield_sabah_t_per_ha": None,
        "ffb_yield_sarawak_t_per_ha": None,
        "ending_stocks_total_mt": 1615618,
        "ending_stocks_cpo_mt": 710310,
        "ending_stocks_processed_mt": 905308,
        "exports_palm_oil_mt": 16664068,
        "planted_area_malaysia_ha": 4846822,
        "provenance": "SOURCE: MPOB Overview_of_Industry_2010.pdf",
    },
    {
        "year": 2011,
        "cpo_production_malaysia_mt": 18911520,
        "cpo_production_peninsular_mt": 10370000,
        "cpo_production_sabah_mt": 5840000,
        "cpo_production_sarawak_mt": 2700000,
        "oer_national_pct": 20.35,
        "oer_peninsular_pct": 20.08,
        "oer_sabah_pct": 20.74,
        "oer_sarawak_pct": 20.59,
        "ffb_yield_malaysia_t_per_ha": 19.69,
        "ffb_yield_peninsular_t_per_ha": None,
        "ffb_yield_sabah_t_per_ha": None,
        "ffb_yield_sarawak_t_per_ha": None,
        "ending_stocks_total_mt": 2058400,
        "ending_stocks_cpo_mt": 1066291,
        "ending_stocks_processed_mt": 992109,
        "exports_palm_oil_mt": 17993265,
        "planted_area_malaysia_ha": 5000109,
        "provenance": "SOURCE: MPOB Overview_of_Industry_2011.pdf",
    },
    {
        "year": 2015,
        "cpo_production_malaysia_mt": 19961581,
        "cpo_production_peninsular_mt": 10536467,
        "cpo_production_sabah_mt": 5722967,
        "cpo_production_sarawak_mt": 3702147,
        "oer_national_pct": 20.46,
        "oer_peninsular_pct": 20.01,
        "oer_sabah_pct": 21.57,
        "oer_sarawak_pct": 20.15,
        "ffb_yield_malaysia_t_per_ha": 18.48,
        "ffb_yield_peninsular_t_per_ha": 18.77,
        "ffb_yield_sabah_t_per_ha": 19.99,
        "ffb_yield_sarawak_t_per_ha": 16.21,
        "ending_stocks_total_mt": 2633940,
        "ending_stocks_cpo_mt": 1593073,
        "ending_stocks_processed_mt": 1040867,
        "exports_palm_oil_mt": 17454213,
        "planted_area_malaysia_ha": 5642943,
        "provenance": "SOURCE: MPOB Overview_of_Industry_2015.pdf",
    },
    {
        "year": 2016,
        "cpo_production_malaysia_mt": 17319177,
        "cpo_production_peninsular_mt": 8886638,
        "cpo_production_sabah_mt": 4847253,
        "cpo_production_sarawak_mt": 3585286,
        "oer_national_pct": 20.18,
        "oer_peninsular_pct": 19.76,
        "oer_sabah_pct": 21.11,
        "oer_sarawak_pct": 20.02,
        "ffb_yield_malaysia_t_per_ha": 15.91,
        "ffb_yield_peninsular_t_per_ha": 15.77,
        "ffb_yield_sabah_t_per_ha": 17.10,
        "ffb_yield_sarawak_t_per_ha": 14.86,
        "ending_stocks_total_mt": 1666673,
        "ending_stocks_cpo_mt": 877082,
        "ending_stocks_processed_mt": 789591,
        "exports_palm_oil_mt": 16045957,
        "planted_area_malaysia_ha": 5737985,
        "provenance": "SOURCE: MPOB Overview_of_Industry_2016.pdf",
    },
    # ── 2017-2020 batch ──────────────────────────────────────────────────────
    {
        "year": 2017,
        "cpo_production_malaysia_mt": 19919331,
        "cpo_production_peninsular_mt": 10575920,
        "cpo_production_sabah_mt": 5215345,
        "cpo_production_sarawak_mt": 4128066,
        "oer_national_pct": 19.72,
        "oer_peninsular_pct": 19.21,
        "oer_sabah_pct": 20.60,
        "oer_sarawak_pct": 19.98,
        "ffb_yield_malaysia_t_per_ha": 17.89,
        "ffb_yield_peninsular_t_per_ha": 18.70,
        "ffb_yield_sabah_t_per_ha": 18.35,
        "ffb_yield_sarawak_t_per_ha": 16.13,
        "ending_stocks_total_mt": 2732093,
        "ending_stocks_cpo_mt": 1669196,
        "ending_stocks_processed_mt": 1062897,
        "exports_palm_oil_mt": 16559957,
        "planted_area_malaysia_ha": 5811145,
        "provenance": "SOURCE: MPOB Overview_of_Industry_2017.pdf",
    },
    {
        "year": 2018,
        "cpo_production_malaysia_mt": 19516141,
        "cpo_production_peninsular_mt": 10197446,
        "cpo_production_sabah_mt": 5139356,
        "cpo_production_sarawak_mt": 4179339,
        "oer_national_pct": 19.95,
        "oer_peninsular_pct": 19.69,
        "oer_sabah_pct": 20.60,
        "oer_sarawak_pct": 19.85,
        "ffb_yield_malaysia_t_per_ha": 17.16,
        "ffb_yield_peninsular_t_per_ha": 17.44,
        "ffb_yield_sabah_t_per_ha": 18.16,
        "ffb_yield_sarawak_t_per_ha": 15.74,
        "ending_stocks_total_mt": 3215052,
        "ending_stocks_cpo_mt": 1940680,
        "ending_stocks_processed_mt": 1274372,
        "exports_palm_oil_mt": 16487556,
        "planted_area_malaysia_ha": 5849330,
        "provenance": "SOURCE: MPOB Overview_of_Industry_2018.pdf",
    },
    {
        "year": 2019,
        "cpo_production_malaysia_mt": 19858367,
        "cpo_production_peninsular_mt": 10583788,
        "cpo_production_sabah_mt": 5037168,
        "cpo_production_sarawak_mt": 4237411,
        "oer_national_pct": 20.21,
        "oer_peninsular_pct": 19.93,
        "oer_sabah_pct": 20.97,
        "oer_sarawak_pct": 20.03,
        "ffb_yield_malaysia_t_per_ha": 17.19,
        "ffb_yield_peninsular_t_per_ha": 17.95,
        "ffb_yield_sabah_t_per_ha": 17.66,
        "ffb_yield_sarawak_t_per_ha": 15.56,
        "ending_stocks_total_mt": 2010527,
        "ending_stocks_cpo_mt": 1019510,
        "ending_stocks_processed_mt": 991017,
        "exports_palm_oil_mt": 18471065,
        "planted_area_malaysia_ha": 5900157,
        "provenance": "SOURCE: MPOB Overview_of_Industry_2019.pdf",
    },
    {
        "year": 2020,
        "cpo_production_malaysia_mt": 19140613,
        "cpo_production_peninsular_mt": 10438899,
        "cpo_production_sabah_mt": 4647375,
        "cpo_production_sarawak_mt": 4054339,
        "oer_national_pct": 19.92,
        "oer_peninsular_pct": 19.69,
        "oer_sabah_pct": 20.74,
        "oer_sarawak_pct": 19.62,
        "ffb_yield_malaysia_t_per_ha": 16.73,
        "ffb_yield_peninsular_t_per_ha": 17.76,
        "ffb_yield_sabah_t_per_ha": 16.84,
        "ffb_yield_sarawak_t_per_ha": 14.99,
        "ending_stocks_total_mt": 1265698,
        "ending_stocks_cpo_mt": 583811,
        "ending_stocks_processed_mt": 681887,
        "exports_palm_oil_mt": 17395072,
        "planted_area_malaysia_ha": 5865297,
        "provenance": "SOURCE: MPOB Overview_of_Industry_2020.pdf",
    },
    # ── 2021-2025 batch ──────────────────────────────────────────────────────
    {
        "year": 2021,
        "cpo_production_malaysia_mt": 18116354,
        "cpo_production_peninsular_mt": 9846997,
        "cpo_production_sabah_mt": 4361537,
        "cpo_production_sarawak_mt": 3907820,
        "oer_national_pct": 20.01,
        "oer_peninsular_pct": 19.83,
        "oer_sabah_pct": 20.55,
        "oer_sarawak_pct": 19.88,
        "ffb_yield_malaysia_t_per_ha": 15.47,
        "ffb_yield_peninsular_t_per_ha": 16.24,
        "ffb_yield_sabah_t_per_ha": 15.77,
        "ffb_yield_sarawak_t_per_ha": 13.94,
        "ending_stocks_total_mt": 1614594,
        "ending_stocks_cpo_mt": 852877,
        "ending_stocks_processed_mt": 761717,
        "exports_palm_oil_mt": 15566439,
        "planted_area_malaysia_ha": 5737731,
        "provenance": "SOURCE: MPOB Overview2021.pdf",
    },
    {
        "year": 2022,
        "cpo_production_malaysia_mt": 18453420,
        "cpo_production_peninsular_mt": 10161330,
        "cpo_production_sabah_mt": 4286665,
        "cpo_production_sarawak_mt": 4005425,
        "oer_national_pct": 19.70,
        "oer_peninsular_pct": 19.57,
        "oer_sabah_pct": 20.25,
        "oer_sarawak_pct": 19.47,
        "ffb_yield_malaysia_t_per_ha": 15.49,
        "ffb_yield_peninsular_t_per_ha": 16.41,
        "ffb_yield_sabah_t_per_ha": 15.39,
        "ffb_yield_sarawak_t_per_ha": 14.13,
        "ending_stocks_total_mt": 2196574,
        "ending_stocks_cpo_mt": 1293873,
        "ending_stocks_processed_mt": 902701,
        "exports_palm_oil_mt": 15712068,
        "planted_area_malaysia_ha": 5674742,
        "provenance": "SOURCE: MPOB Overview2022.pdf",
    },
    {
        "year": 2023,
        "cpo_production_malaysia_mt": 18551950,
        "cpo_production_peninsular_mt": 9825140,
        "cpo_production_sabah_mt": 4507460,
        "cpo_production_sarawak_mt": 4219350,
        "oer_national_pct": 19.86,
        "oer_peninsular_pct": 19.64,
        "oer_sabah_pct": 20.40,
        "oer_sarawak_pct": 19.83,
        "ffb_yield_malaysia_t_per_ha": 15.79,
        "ffb_yield_peninsular_t_per_ha": 16.09,
        "ffb_yield_sabah_t_per_ha": 16.39,
        "ffb_yield_sarawak_t_per_ha": 14.75,
        "ending_stocks_total_mt": 2290793,
        "ending_stocks_cpo_mt": 1197668,
        "ending_stocks_processed_mt": 1093125,
        "exports_palm_oil_mt": 15130738,
        "planted_area_malaysia_ha": 5652569,
        "provenance": "SOURCE: MPOB Overview2023.pdf",
    },
    {
        "year": 2024,
        "cpo_production_malaysia_mt": 19338266,
        "cpo_production_peninsular_mt": 10891417,
        "cpo_production_sabah_mt": 4274440,
        "cpo_production_sarawak_mt": 4172409,
        "oer_national_pct": 19.67,
        "oer_peninsular_pct": 19.46,
        "oer_sabah_pct": 20.53,
        "oer_sarawak_pct": 19.37,
        "ffb_yield_malaysia_t_per_ha": 16.70,
        "ffb_yield_peninsular_t_per_ha": 18.42,
        "ffb_yield_sabah_t_per_ha": 15.74,
        "ffb_yield_sarawak_t_per_ha": 14.89,
        "ending_stocks_total_mt": 1708756,
        "ending_stocks_cpo_mt": 894330,
        "ending_stocks_processed_mt": 814426,
        "exports_palm_oil_mt": 16902595,
        "planted_area_malaysia_ha": 5612852,
        "provenance": "SOURCE: MPOB Overview2024.pdf",
    },
    {
        "year": 2025,
        "cpo_production_malaysia_mt": 20283475,
        "cpo_production_peninsular_mt": 11376845,
        "cpo_production_sabah_mt": 4410291,
        "cpo_production_sarawak_mt": 4496339,
        "oer_national_pct": 19.74,
        "oer_peninsular_pct": 19.62,
        "oer_sabah_pct": 20.31,
        "oer_sarawak_pct": 19.51,
        "ffb_yield_malaysia_t_per_ha": 17.77,
        "ffb_yield_peninsular_t_per_ha": 19.49,
        "ffb_yield_sabah_t_per_ha": 16.76,
        "ffb_yield_sarawak_t_per_ha": 15.98,
        "ending_stocks_total_mt": 3051147,
        "ending_stocks_cpo_mt": 1821781,
        "ending_stocks_processed_mt": 1229366,
        "exports_palm_oil_mt": 15272823,
        "planted_area_malaysia_ha": 5700050,
        "provenance": "SOURCE: MPOB Overview2025.pdf",
    },
]

mpob = pd.DataFrame(mpob_raw).sort_values("year").reset_index(drop=True)
mpob.to_csv(os.path.join(PROCESSED, "mpob_annual.csv"), index=False)
print(f"mpob_annual.csv saved: {len(mpob)} rows, years {mpob['year'].min()}–{mpob['year'].max()}")

# ─── GAIN Indonesia Data ───────────────────────────────────────────────────────
gain_raw = [
    {
        "report_number": "ID2022-0007",
        "report_date": "2022-03-23",
        "production_forecast_current_year_mmt": 45.5,
        "production_forecast_next_year_mmt": 46.0,
        "industrial_consumption_current_mmt": 9.6,
        "exports_current_year_mmt": 29.0,
        "biodiesel_mandate_level": "B30",
        "biodiesel_volume_bn_liters": None,
        "key_weather_signal": "BMKG: rainfall levels in most key palm production areas of Sumatra and Kalimantan forecast normal to high for 2022/23. Ground water availability for plants on both islands is sufficient.",
        "key_policy_signal": "GOI increased DMO allocation to 30% from 20%, requiring exporters to sell 30% of export volume to domestic market. Policy enacted January 27, 2022.",
        "bmkg_drought_forecast": None,
        "affected_regions": None,
        "enso_reference": None,
        "export_levy_pct": None,
        "b50_status": None,
        "provenance": "SOURCE: USDA GAIN ID2022-0007 Jakarta March 23, 2022",
    },
    {
        "report_number": "ID2023-0005",
        "report_date": "2023-03-20",
        "production_forecast_current_year_mmt": 44.7,
        "production_forecast_next_year_mmt": 46.0,
        "industrial_consumption_current_mmt": 11.8,
        "exports_current_year_mmt": 28.4,
        "biodiesel_mandate_level": "B35",
        "biodiesel_volume_bn_liters": None,
        "key_weather_signal": "BMKG predicted 50-60% chance weather pattern would shift to El Niño in second half of 2023. In 2015, El Niño caused severe dryness, water deficits, longer periods of no rainfall, reduced fruit setting and flowering, and ultimately lowered Indonesia palm oil output.",
        "key_policy_signal": "B35 implementation started February 2023. Pertamina needs additional time to adjust infrastructure in certain regions; full B35 distribution delayed ~6 months.",
        "bmkg_drought_forecast": None,
        "affected_regions": None,
        "enso_reference": "In 2015, El Nino caused severe dryness, water deficits, longer periods of no rainfall, reduced fruit setting and flowering, and ultimately lowered Indonesia palm oil output.",
        "export_levy_pct": None,
        "b50_status": None,
        "provenance": "SOURCE: USDA GAIN ID2023-0005 Jakarta March 20, 2023",
    },
    {
        "report_number": "ID2024-0004",
        "report_date": "2024-03-20",
        "production_forecast_current_year_mmt": 45.8,
        "production_forecast_next_year_mmt": 47.0,
        "industrial_consumption_current_mmt": 12.4,
        "exports_current_year_mmt": 27.6,
        "biodiesel_mandate_level": "B35",
        "biodiesel_volume_bn_liters": None,
        "key_weather_signal": "Marginal production increase largely due to expected recovery from 2023 El Niño effects on Southern Sumatera.",
        "key_policy_signal": "GOI completed B40 road tests for passenger vehicles and trucks. Plans additional tests for trains, ships, and heavy machinery. No clear B40 implementation date set.",
        "bmkg_drought_forecast": None,
        "affected_regions": None,
        "enso_reference": "Recovery from 2023 El Nino effects on the region of Southern Sumatera.",
        "export_levy_pct": None,
        "b50_status": None,
        "provenance": "SOURCE: USDA GAIN ID2024-0004 Jakarta March 20, 2024",
    },
    {
        "report_number": "ID2025-0015",
        "report_date": "2025-04-14",
        "production_forecast_current_year_mmt": 45.5,
        "production_forecast_next_year_mmt": 47.0,
        "industrial_consumption_current_mmt": 14.7,
        "exports_current_year_mmt": 23.0,
        "biodiesel_mandate_level": "B40",
        "biodiesel_volume_bn_liters": 15.6,
        "key_weather_signal": "BMKG: La Niña transitioned to ENSO neutral in March 2025. IOD also projected to enter neutral phase during dry season. 2025 dry season predicted normal, without strong ENSO or IOD effects.",
        "key_policy_signal": "B40 mandate rolled out nationwide March 2025. Insufficient subsidy prompted plan for 10% increase in export levies. B50 tests began February 2025, expected completion within months. ESDM aiming for B50 rollout in 2026.",
        "bmkg_drought_forecast": None,
        "affected_regions": None,
        "enso_reference": None,
        "export_levy_pct": None,
        "b50_status": "B50 tests began February 2025. Ministry of Energy and Mineral Resources (ESDM) aiming to roll out B50 blending mandate program in 2026 after reviewing current tests.",
        "provenance": "SOURCE: USDA GAIN ID2025-0015 Jakarta April 14, 2025",
    },
    {
        "report_number": "ID2026-0013",
        "report_date": "2026-04-15",
        "production_forecast_current_year_mmt": 46.7,
        "production_forecast_next_year_mmt": 48.0,
        "industrial_consumption_current_mmt": 14.9,
        "exports_current_year_mmt": 24.0,
        "biodiesel_mandate_level": "B40",
        "biodiesel_volume_bn_liters": 14.4,
        "key_weather_signal": "BMKG forecast earlier-than-normal 2026 dry season onset with below-normal rainfall and prolonged duration, potentially leading to intense heat and drought across many regions.",
        "key_policy_signal": "GOI increased CPO export levy 2.5% to 12.5% in March 2026. Continued mandatory B40; B50 not implemented nationwide. Road tests for B50 expected to finish June 2026.",
        "bmkg_drought_forecast": (
            "Indonesia's weather agency (BMKG) forecast an earlier-than-normal onset of the 2026 dry "
            "season, with below-normal rainfall and a prolonged duration, potentially leading to intense "
            "heat and drought conditions across many regions. The dry season is expected to begin earlier "
            "than usual, starting in April 2026 across 114 seasonal zones in Indonesia, and gradually "
            "spreading to other areas in May and June. Several palm producing regions, including Aceh, "
            "North Sumatera, and parts of Riau, West Sumatera, and Jambi, as well as most areas in South "
            "Sumatera, are projected to experience drier than normal conditions with heightened risk of drought."
        ),
        "affected_regions": "Aceh; North Sumatera; Riau; West Sumatera; Jambi; South Sumatera",
        "enso_reference": "Previous prolonged drought related to El Niño events in 2015 and 2023 caused water shortages that lowered palm production in several regions.",
        "export_levy_pct": 12.5,
        "b50_status": "GOI continued mandatory B40 in 2026; decided not to implement B50 nationwide. Road tests ongoing, expected to finish June 2026. B50 would require ~20 billion liters of palm biodiesel per year.",
        "provenance": "SOURCE: USDA GAIN ID2026-0013 Jakarta April 15, 2026",
    },
]

gain = pd.DataFrame(gain_raw)
gain.to_csv(os.path.join(PROCESSED, "gain_indonesia.csv"), index=False)
print(f"gain_indonesia.csv saved: {len(gain)} rows")

print("\nAll CSVs built successfully.")
